import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class HomePosts extends StatefulWidget {
  const HomePosts({super.key});

  @override
  State<HomePosts> createState() => _HomePostsState();
}

class _HomePostsState extends State<HomePosts> {
  final List<Map<String, dynamic>> posts = [
    {
      "profileImg": "assets/images/home/dp1.jpg",
      "username": "John Doe",
      "timeAgo": "2 hours ago",
      "caption": "Exploring the world with new experiences! #Travel #Adventure",
      "postImg": "assets/images/home/post1.jpg",
      "likes": "250",
      "likedBy": "Jane",
      "comments": "15",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp2.jpg",
      "username": "Alice Smith",
      "timeAgo": "5 hours ago",
      "caption": "Sunset at the beach! 🌅 #BeachVibes",
      "postImg": "assets/images/home/post2.jpg",
      "likes": "340",
      "likedBy": "Mike",
      "comments": "20",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp3.jpg",
      "username": "Michael Lee",
      "timeAgo": "1 day ago",
      "caption": "Best coffee in town ☕️ #CoffeeLover",
      "postImg": "assets/images/home/post3.jpg",
      "likes": "180",
      "likedBy": "Emma",
      "comments": "10",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp4.jpg",
      "username": "Sarah Johnson",
      "timeAgo": "3 hours ago",
      "caption": "Chasing waterfalls today! #Nature #Hiking",
      "postImg": "assets/images/home/post4.jpg",
      "likes": "275",
      "likedBy": "Tom",
      "comments": "18",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp5.jpg",
      "username": "David Kim",
      "timeAgo": "6 hours ago",
      "caption": "Late night coding session #Programming #TechLife",
      "postImg": "assets/images/home/post5.jpg",
      "likes": "190",
      "likedBy": "Sophia",
      "comments": "12",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp6.jpg",
      "username": "Emma Brown",
      "timeAgo": "8 hours ago",
      "caption": "Baking some cookies 🍪 #HomeMade",
      "postImg": "assets/images/home/post6.jpg",
      "likes": "310",
      "likedBy": "Liam",
      "comments": "25",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp7.jpg",
      "username": "Liam Carter",
      "timeAgo": "12 hours ago",
      "caption": "Morning run feels amazing! #Fitness #Running",
      "postImg": "assets/images/home/post7.jpg",
      "likes": "220",
      "likedBy": "Olivia",
      "comments": "14",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp8.jpg",
      "username": "Olivia White",
      "timeAgo": "15 hours ago",
      "caption": "City lights at night 🌃 #CityLife",
      "postImg": "assets/images/home/post8.jpg",
      "likes": "400",
      "likedBy": "Noah",
      "comments": "30",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp9.jpg",
      "username": "Noah Davis",
      "timeAgo": "1 day ago",
      "caption": "New guitar, new tunes 🎸 #Music",
      "postImg": "assets/images/home/post9.jpg",
      "likes": "260",
      "likedBy": "Ava",
      "comments": "17",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp10.jpg",
      "username": "Ava Taylor",
      "timeAgo": "2 days ago",
      "caption": "Bookstore adventures 📚 #Reading",
      "postImg": "assets/images/home/post10.jpg",
      "likes": "230",
      "likedBy": "Ethan",
      "comments": "13",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp11.jpg",
      "username": "Ethan Parker",
      "timeAgo": "3 hours ago",
      "caption": "Snowboarding down the slopes! #WinterSports",
      "postImg": "assets/images/home/post11.jpg",
      "likes": "320",
      "likedBy": "Mia",
      "comments": "22",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp12.jpg",
      "username": "Mia Garcia",
      "timeAgo": "4 hours ago",
      "caption": "Art gallery vibes 🎨 #ArtLover",
      "postImg": "assets/images/home/post12.jpg",
      "likes": "290",
      "likedBy": "James",
      "comments": "19",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp13.jpg",
      "username": "James Wilson",
      "timeAgo": "7 hours ago",
      "caption": "Grilling some steaks tonight 🍔 #Foodie",
      "postImg": "assets/images/home/post13.jpg",
      "likes": "350",
      "likedBy": "Isabella",
      "comments": "24",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp14.jpg",
      "username": "Isabella Martinez",
      "timeAgo": "9 hours ago",
      "caption": "Yoga by the sunrise 🌞 #Wellness",
      "postImg": "assets/images/home/post14.jpg",
      "likes": "270",
      "likedBy": "Lucas",
      "comments": "16",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp15.jpg",
      "username": "Lucas Evans",
      "timeAgo": "11 hours ago",
      "caption": "Gaming marathon tonight 🎮 #GamerLife",
      "postImg": "assets/images/home/post15.jpg",
      "likes": "300",
      "likedBy": "Charlotte",
      "comments": "21",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp16.jpg",
      "username": "Charlotte Adams",
      "timeAgo": "14 hours ago",
      "caption": "Puppy cuddles all day 🐶 #PetLove",
      "postImg": "assets/images/home/post16.jpg",
      "likes": "380",
      "likedBy": "Mason",
      "comments": "28",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp17.jpg",
      "username": "Mason Scott",
      "timeAgo": "1 day ago",
      "caption": "Mountain biking thrill! #Adventure",
      "postImg": "assets/images/home/post17.jpg",
      "likes": "240",
      "likedBy": "Amelia",
      "comments": "15",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp18.jpg",
      "username": "Amelia Clark",
      "timeAgo": "2 days ago",
      "caption": "Starry night camping ⛺ #NatureLover",
      "postImg": "assets/images/home/post18.jpg",
      "likes": "330",
      "likedBy": "Henry",
      "comments": "23",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp19.jpg",
      "username": "Henry Brooks",
      "timeAgo": "3 hours ago",
      "caption": "Fresh sushi dinner 🍣 #FoodLover",
      "postImg": "assets/images/home/post19.jpg",
      "likes": "280",
      "likedBy": "Sophie",
      "comments": "20",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp20.jpg",
      "username": "Sophie Turner",
      "timeAgo": "5 hours ago",
      "caption": "Exploring old castles 🏰 #History",
      "postImg": "assets/images/home/post20.jpg",
      "likes": "310",
      "likedBy": "Jack",
      "comments": "18",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp21.jpg",
      "username": "Jack Miller",
      "timeAgo": "6 hours ago",
      "caption": "New skateboard tricks 🛹 #SkateLife",
      "postImg": "assets/images/home/post21.jpg",
      "likes": "260",
      "likedBy": "Lily",
      "comments": "17",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp22.jpg",
      "username": "Lily Chen",
      "timeAgo": "8 hours ago",
      "caption": "Flower garden in bloom 🌸 #Gardening",
      "postImg": "assets/images/home/post22.jpg",
      "likes": "290",
      "likedBy": "Oliver",
      "comments": "19",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp23.jpg",
      "username": "Oliver Green",
      "timeAgo": "10 hours ago",
      "caption": "Kayaking on the lake 🛶 #OutdoorLife",
      "postImg": "assets/images/home/post23.jpg",
      "likes": "320",
      "likedBy": "Zoe",
      "comments": "22",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp24.jpg",
      "username": "Zoe Nguyen",
      "timeAgo": "12 hours ago",
      "caption": "Homemade pizza night 🍕 #Cooking",
      "postImg": "assets/images/home/post24.jpg",
      "likes": "350",
      "likedBy": "Ryan",
      "comments": "25",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp25.jpg",
      "username": "Ryan Patel",
      "timeAgo": "1 day ago",
      "caption": "Concert vibes tonight 🎤 #LiveMusic",
      "postImg": "assets/images/home/post25.jpg",
      "likes": "400",
      "likedBy": "Ella",
      "comments": "30",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp26.jpg",
      "username": "Ella Foster",
      "timeAgo": "2 days ago",
      "caption": "Hiking to the peak! #Mountains",
      "postImg": "assets/images/home/post26.jpg",
      "likes": "270",
      "likedBy": "Logan",
      "comments": "16",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp27.jpg",
      "username": "Logan Hayes",
      "timeAgo": "3 hours ago",
      "caption": "New painting finished 🎨 #Artist",
      "postImg": "assets/images/home/post27.jpg",
      "likes": "300",
      "likedBy": "Grace",
      "comments": "21",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp28.jpg",
      "username": "Grace Phillips",
      "timeAgo": "4 hours ago",
      "caption": "Beach volleyball fun 🏐 #Sports",
      "postImg": "assets/images/home/post28.jpg",
      "likes": "280",
      "likedBy": "Dylan",
      "comments": "18",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp29.jpg",
      "username": "Dylan Morris",
      "timeAgo": "6 hours ago",
      "caption": "Vintage car show 🚗 #CarLover",
      "postImg": "assets/images/home/post29.jpg",
      "likes": "310",
      "likedBy": "Hannah",
      "comments": "20",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp30.jpg",
      "username": "Hannah Reed",
      "timeAgo": "8 hours ago",
      "caption": "Sunrise meditation 🌅 #Mindfulness",
      "postImg": "assets/images/home/post30.jpg",
      "likes": "260",
      "likedBy": "Caleb",
      "comments": "15",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp31.jpg",
      "username": "Caleb Young",
      "timeAgo": "10 hours ago",
      "caption": "New drone shots 📸 #Photography",
      "postImg": "assets/images/home/post31.jpg",
      "likes": "330",
      "likedBy": "Avery",
      "comments": "23",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp32.jpg",
      "username": "Avery King",
      "timeAgo": "12 hours ago",
      "caption": "Skiing down the mountain ⛷️ #WinterFun",
      "postImg": "assets/images/home/post32.jpg",
      "likes": "290",
      "likedBy": "Scarlett",
      "comments": "19",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp33.jpg",
      "username": "Scarlett Bell",
      "timeAgo": "1 day ago",
      "caption": "Freshly baked bread 🍞 #Baking",
      "postImg": "assets/images/home/post33.jpg",
      "likes": "340",
      "likedBy": "Gabriel",
      "comments": "24",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp34.jpg",
      "username": "Gabriel Ortiz",
      "timeAgo": "2 days ago",
      "caption": "Exploring the desert 🏜️ #Travel",
      "postImg": "assets/images/home/post34.jpg",
      "likes": "270",
      "likedBy": "Chloe",
      "comments": "17",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp35.jpg",
      "username": "Chloe Bennett",
      "timeAgo": "3 hours ago",
      "caption": "New yoga poses mastered 🧘 #Fitness",
      "postImg": "assets/images/home/post35.jpg",
      "likes": "300",
      "likedBy": "Elijah",
      "comments": "20",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp36.jpg",
      "username": "Elijah Ross",
      "timeAgo": "5 hours ago",
      "caption": "Street food adventures 🌮 #Foodie",
      "postImg": "assets/images/home/post36.jpg",
      "likes": "320",
      "likedBy": "Violet",
      "comments": "22",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp37.jpg",
      "username": "Violet Ward",
      "timeAgo": "7 hours ago",
      "caption": "Sunset sailing ⛵ #OceanLife",
      "postImg": "assets/images/home/post37.jpg",
      "likes": "350",
      "likedBy": "Isaac",
      "comments": "25",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp38.jpg",
      "username": "Isaac Perry",
      "timeAgo": "9 hours ago",
      "caption": "Rock climbing challenge 🧗 #Adventure",
      "postImg": "assets/images/home/post38.jpg",
      "likes": "280",
      "likedBy": "Aria",
      "comments": "18",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp39.jpg",
      "username": "Aria Hughes",
      "timeAgo": "11 hours ago",
      "caption": "Cozy night with a book 📖 #Relax",
      "postImg": "assets/images/home/post39.jpg",
      "likes": "260",
      "likedBy": "Levi",
      "comments": "16",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp40.jpg",
      "username": "Levi Gray",
      "timeAgo": "13 hours ago",
      "caption": "New bike ride route 🚴 #Cycling",
      "postImg": "assets/images/home/post40.jpg",
      "likes": "310",
      "likedBy": "Luna",
      "comments": "21",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp41.jpg",
      "username": "Luna Myers",
      "timeAgo": "1 day ago",
      "caption": "Stargazing tonight ✨ #Astronomy",
      "postImg": "assets/images/home/post41.jpg",
      "likes": "340",
      "likedBy": "Owen",
      "comments": "24",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp42.jpg",
      "username": "Owen Fox",
      "timeAgo": "2 days ago",
      "caption": "Fresh smoothie morning 🍍 #HealthyLiving",
      "postImg": "assets/images/home/post42.jpg",
      "likes": "290",
      "likedBy": "Nora",
      "comments": "19",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp43.jpg",
      "username": "Nora Price",
      "timeAgo": "3 hours ago",
      "caption": "Exploring a new city 🏙️ #Travel",
      "postImg": "assets/images/home/post43.jpg",
      "likes": "320",
      "likedBy": "Wyatt",
      "comments": "22",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp44.jpg",
      "username": "Wyatt Lane",
      "timeAgo": "5 hours ago",
      "caption": "Building a new PC 💻 #Tech",
      "postImg": "assets/images/home/post44.jpg",
      "likes": "300",
      "likedBy": "Sofia",
      "comments": "20",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp45.jpg",
      "username": "Sofia Diaz",
      "timeAgo": "7 hours ago",
      "caption": "Dance practice tonight 💃 #Dancing",
      "postImg": "assets/images/home/post45.jpg",
      "likes": "280",
      "likedBy": "Carter",
      "comments": "18",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp46.jpg",
      "username": "Carter Hill",
      "timeAgo": "9 hours ago",
      "caption": "Fishing by the river 🎣 #Outdoor",
      "postImg": "assets/images/home/post46.jpg",
      "likes": "310",
      "likedBy": "Piper",
      "comments": "21",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp47.jpg",
      "username": "Piper Cole",
      "timeAgo": "11 hours ago",
      "caption": "New pottery piece 🏺 #Crafting",
      "postImg": "assets/images/home/post47.jpg",
      "likes": "270",
      "likedBy": "Hudson",
      "comments": "17",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp48.jpg",
      "username": "Hudson Shaw",
      "timeAgo": "1 day ago",
      "caption": "Surfing the waves 🌊 #SurfLife",
      "postImg": "assets/images/home/post48.jpg",
      "likes": "350",
      "likedBy": "Mila",
      "comments": "25",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp49.jpg",
      "username": "Mila Stone",
      "timeAgo": "2 days ago",
      "caption": "Cozy fireplace night 🔥 #Winter",
      "postImg": "assets/images/home/post49.jpg",
      "likes": "290",
      "likedBy": "Asher",
      "comments": "19",
      "isLiked": false,
    },
    {
      "profileImg": "assets/images/home/dp50.jpg",
      "username": "Asher Knight",
      "timeAgo": "3 hours ago",
      "caption": "New recipe success 🍲 #Cooking",
      "postImg": "assets/images/home/post50.jpg",
      "likes": "320",
      "likedBy": "John",
      "comments": "22",
      "isLiked": false,
    },
  ];

  void toggleLike(int index) {
    setState(() {
      posts[index]["isLiked"] = !posts[index]["isLiked"];
    });
  }

  @override
  Widget build(BuildContext context) {
    return ListView.builder(
      itemCount: posts.length,
      shrinkWrap: true,
      physics: NeverScrollableScrollPhysics(),
      itemBuilder: (context, index) {
        final post = posts[index];

        return Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // User Info Section
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 0),
              child: ListTile(
                contentPadding: EdgeInsets.zero,
                leading: CircleAvatar(
                  backgroundImage: AssetImage(post["profileImg"]),
                  radius: 20,
                ),
                title: Text(
                  post["username"],
                  style: const TextStyle(
                    fontSize: 14,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                subtitle: Text(
                  '${post["timeAgo"]} • ${post["caption"]}',
                  style: TextStyle(fontSize: 12, color: Colors.grey[600]),
                  maxLines: 1,
                  overflow: TextOverflow.ellipsis,
                ),
                trailing: IconButton(
                  icon: const Icon(Icons.more_vert_outlined),
                  onPressed: () {
                    // Show options menu
                  },
                ),
              ),
            ),
            // Post Image
            Container(
              width: double.infinity,
              // child: UiHelper.customImage(imageUrl: post["postImg"]),
              // height: 300,
              child: ClipRRect(
                child: CachedNetworkImage(
                  imageUrl: post["postImg"],
                  errorWidget:
                      (context, url, error) => const Icon(CupertinoIcons.photo),
                  // placeholder: (context, url) => Container(
                  //   // Set the height similar to the expected image height
                  //   width: double.infinity,
                  //   color: CupertinoColors.systemGrey4,
                  //   child: Shimmer.fromColors(
                  //     baseColor: CupertinoColors.systemGrey4,
                  //     highlightColor: CupertinoColors.systemGrey5,
                  //     child: Container(
                  //       width: double.infinity,
                  //       height: double.infinity,
                  //       color: CupertinoColors.systemGrey4,
                  //     ),
                  //   ),
                  // ),
                  placeholder:
                      (context, url) =>
                          Center(child: CupertinoActivityIndicator()),
                  fit: BoxFit.cover,
                ),
              ),
            ),
            // Action Buttons (Like, Comment, Share)
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 5),
              child: Row(
                children: [
                  IconButton(
                    icon: Icon(
                      post["isLiked"]
                          ? CupertinoIcons.heart_fill
                          : CupertinoIcons.heart,
                      size: 20,
                      color: post["isLiked"] ? Colors.red : null,
                    ),
                    onPressed: () => toggleLike(index),
                  ),
                  Row(
                    children: [
                      IconButton(
                        icon: const Icon(Icons.comment_outlined),
                        onPressed: () {
                          // Navigate to comments section
                        },
                      ),
                      Text(
                        post["comments"], // Display total comments
                        style: TextStyle(fontSize: 14, color: Colors.white),
                      ),
                    ],
                  ),
                  IconButton(
                    icon: const Icon(CupertinoIcons.paperplane, size: 20),
                    onPressed: () {
                      // Share functionality
                    },
                  ),
                  const Spacer(),
                  IconButton(
                    icon: const Icon(CupertinoIcons.bookmark, size: 20),
                    onPressed: () {
                      // Save post functionality
                    },
                  ),
                ],
              ),
            ),
            // Like Count & Caption
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 10),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'Liked by ${post["likedBy"]} and ${post["likes"]} others',
                    style: const TextStyle(fontWeight: FontWeight.bold),
                  ),
                  const SizedBox(height: 4),
                  Text(post["caption"]),
                  const SizedBox(height: 6),
                  Text(
                    'View all ${post["comments"]} comments',
                    style: const TextStyle(color: Colors.grey),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 10),
          ],
        );
      },
    );
  }
}
